# Generated by Django 4.1.5 on 2023-01-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20)),
                ('driver_name', models.CharField(max_length=100)),
                ('private', models.BooleanField(default=False)),
                ('num_passengers', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
