# Generated by Django 4.1.5 on 2023-01-08 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tourists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourists',
            name='vehicle_plate_number',
        ),
        migrations.AddField(
            model_name='tourists',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.vehicles'),
        ),
    ]
