# Generated by Django 4.1.5 on 2023-01-08 08:14

from django.db import migrations
from django.db import models

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_tourists_vehicle_plate_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='Vehicles',
            name='visit_count',
            field=models.PositiveIntegerField(),
        ),
         migrations.AddField(
            model_name='Vehicles',
            name='vehicle_contactnumber',
            field=models.CharField(max_length=20, default=''),
        ),
    ]
