# Generated by Django 4.1.5 on 2023-01-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230108_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='vehicle_contactnumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tourists',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tourists',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, blank=True, null=True),
        ),
    ]
