# Generated by Django 4.1.5 on 2023-01-08 08:35

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_vehicles_vehicle_contactnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='vehicle_contactnumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='tourists',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='tourists',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
