# Generated by Django 4.1.5 on 2023-01-10 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_auto_20230108_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourists',
            name='date_time',
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='vehicle_contactnumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='VehicleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.vehicles')),
            ],
        ),
    ]
